# show coverage in CI status, not as a comment.
comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
    patch:
      default:
        target: auto
        target: 10%

ignore:
- "**/setup.py"
- "**/conftest.py"
