name: CI
on:
  push:
    branches: [ main ]
    tags: [ 'v[0-9]+\.[0-9]+.*' ]
  pull_request: { branches: [main] }
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: pre-commit/action@v2.0.0

  test1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages
      run: |
        pip install -U pip wheel
        pip install .
        pip install .[dev,plots]
        python -c 'import skopt; print(skopt.__version__)'
    - name: Run tests
      run: pytest

  test2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        scikit-learn-version: ["1.4.1.post1", "1.3.2", "1.2.2", "1.1.3", "1.0.2"]
        numpy-version: ["1.20.3", "1.22.4","1.24.4", "1.26.4"]
        exclude:
          - python-version: "3.8"
            scikit-learn-version: "1.4.1.post1"
          - python-version: "3.8"
            numpy-version: "1.26.4"
          - python-version: "3.11"
            scikit-learn-version: "1.0.2"
          - python-version: "3.11"
            scikit-learn-version: "1.1.3"
          - python-version: "3.10"
            numpy-version: "1.20.3"
          - python-version: "3.11"
            numpy-version: "1.20.3"
          - python-version: "3.11"
            numpy-version: "1.22.4"
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages
      run: |
        pip install -U pip wheel
        pip install numpy==${{ matrix.numpy-version }}
        pip install scikit-learn==${{ matrix.scikit-learn-version }}
        pip install .
        pip install .[dev,plots]
        python -c 'import skopt; print(skopt.__version__)'
    - name: Run tests
      run: pytest

  doctest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install packages
        run: |
            pip install -U pip wheel
            pip install .
            pip install .[dev,plots,doc]
            python -c 'import skopt; print(skopt.__version__)'
      - name: Run doc test
        run: cd doc; make doctest
