name: Upload Python Package
on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/ci.yml

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: package

    - name: Publish 📦 on PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
