name: Run tests
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages
      run: |
        pip install pytest
        pip install -e .
        pip install -r requirements.txt
    - name: Run fast tests
      run: pytest -m 'fast_test'
    - name: Run slow tests
      run: pytest -m 'slow_test'
